--- 
framework: 
  AdminMode: 1
  ApplicationClass: TestApp
  ApplicationName: TestApp
  ApplicationUUID: 5E8182BA-C8AA-11DC-9E56-2DCB0AF44FC8
  ConfigFileVersion: 2
  Database: 
    AutoUpgrade: 1
    CheckSchema: 1
    Database: testapp
    Driver: SQLite
    Host: localhost
    Password: ''
    RecordBaseClass: Jifty::DBI::Record::Cachable
    User: ''
    Version: 0.0.1
  DevelMode: 1
  L10N: 
    PoDir: share/po
  LogLevel: INFO
  Mailer: Sendmail
  MailerArgs: []

  Plugins: 
    - JapaneseNotification: {}
    - 
      LetMe: {}

    - 
      SkeletonApp: {}

    - 
      REST: {}

    - 
      Halo: {}

    - 
      ErrorTemplates: {}

    - 
      OnlineDocs: {}

    - 
      CompressedCSSandJS: {}

    - 
      AdminUI: {}

  PubSub: 
    Backend: Memcached
    Enable: ~
  SkipAccessControl: 0
  TemplateClass: TestApp::View
  Web: 
    BaseURL: http://localhost
    DataDir: var/mason
    Globals: []

    MasonConfig: 
      autoflush: 0
      default_escape_flags: h
      error_format: text
      error_mode: fatal
    Port: 8888
    ServeStaticFiles: 1
    StaticRoot: share/web/static
    TemplateRoot: share/web/templates
